---
title: "credit_dacon_0424"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
library(tidyverse)
library(skimr)
library(tidymodels)
library(magrittr)

train <- read.csv("dataset/train.csv", na.strings = c("","NA"))
train %>% janitor::clean_names() ->train
test <- read.csv("dataset/test.csv",na.strings = c("","NA"))
test %>% janitor::clean_names() -> test

names(train)
dim(train)
names(test)
dim(test)

# alldata <- bind_rows(train, test)
# dim(alldata)
# 
# skim(alldata)
```


* days_birth : -값은 무슨 의미인지. 연도도 아니고 무슨 값인지 모르겠음. 
* days_employed : -값은 무슨 의미인지. 365일로 나눠서 연으로 살펴봐도 편할 듯
* 카테고리형 features : child_num, flag_mobil, family_size, gender, car
* house_type : 입력은 단답식인데, min/max가 있다니?
* occyp_type : 전문직, 기술직, 사무직 등으로 나눌 수 있을 듯


1) gender: 성별의 credit 분포
```{r cars}
train %>% filter(!is.na(credit)) %>%
    ggplot(aes(x=credit), na.rm=TRUE)+
    geom_bar()+
    theme_bw()


train %>% filter(!is.na(credit)) %>%
    ggplot(aes(x=credit), na.rm=TRUE)+
    geom_bar()+
    facet_grid(.~gender)
    theme_bw()

##upsampling
```



2) days_birth: 나이별 신용 분포
```{r cars}
train %>% select(days_birth) %>% summary()

train<-train %>%
    mutate(days_birth_year = abs(ceiling(days_birth/360))) 

train %>% select(days_birth_year) %>% summary()

train %>% select(days_birth, days_birth_year, credit) %>% head()



train %>% filter(!is.na(credit)) %>%
    ggplot(aes(x=days_birth_year))+
    geom_histogram()+
    facet_grid(.~credit)


train %>% head()


```

3) family_size, child_num, family_type, 

```{r}

train %>% select(family_size, child_num) %>% summary()




```

























