---
title: "energy"
output: html_document
---

```{r setup, include=FALSE}
library("tidymodels")
library("data.table")
library("skimr")
library("lubridate")
```



```{r setup, include=FALSE}
dangjin_fcst <- read_csv("D:/user/Documents/R projects/kaggle-study/competition/dacon_solar_power/dangjin_fcst_data.csv")

dangjin_obs <- read_csv("D:/user/Documents/R projects/kaggle-study/competition/dacon_solar_power/dangjin_obs_data.csv")

ulsan_fcst <- read_csv("D:/user/Documents/R projects/kaggle-study/competition/dacon_solar_power/ulsan_fcst_data.csv")

ulsan_obs <- read_csv("D:/user/Documents/R projects/kaggle-study/competition/dacon_solar_power/ulsan_obs_data.csv")

energy <- read_csv("D:/user/Documents/R projects/kaggle-study/competition/dacon_solar_power/energy.csv")



```

```{r setup, include=FALSE}
rdata_raw <- read.csv("D:/user/Documents/R projects/kaggle-study/study-presentation/connie-mar-5/energy_dacon/data/rdata_raw.csv")


submission <- read.csv("D:/user/Documents/R projects/kaggle-study/study-presentation/connie-mar-5/energy_dacon/data/sample_submission.csv")


rdata_raw<- rdata_raw %>% 
    mutate(date = date(time),
           month = month(time))


rdata_raw <- rdata_raw %>% dplyr::filter(date>= "2018-03-01")


```

```{r setup, include=FALSE}
rdata_14 <- rdata_raw %>% dplyr::filter(hour==14)

rdata_14 %>% 
    ggplot(aes(x=date, y=floating))+
    geom_line()


#rdata_14 %>% pull(floating) %>% ts() %>% autoplot()

```


```{r}
rdata_14 %>%
    select(floating) %>%
    ts() %>%
    mstl() %>%
    autoplot()


```



```{r}
rdata_14 %>%
    select(floating) %>%
    ts(frequency = 12) %>%
    ggtsdisplay()


```

```{r}

submission<- submission %>% mutate(hour = hour(time),
                                   date = date(time))


submission_14<- submission %>% select(date, hour, dangjin_floating)%>%
    dplyr::filter(hour==14)


# rdata_14 %>% pull(floating) %>% ts() %>% autoplot()
rdata_14_stlf <- rdata_14$floating %>% 
    ts(frequency = 12) %>%
    stlf(h=nrow(submission_14))


system.time(rdata_14_stlf)

submission_14 %>%
    mutate(dangjin_floating=rdata_14_stlf$mean)


    
```


```{r}

# 
# submission <- submission %>% 
#     mutate(dangjin_floating=floating.stlf$mean) %>% 
#     mutate(dangjin_warehouse=warehouse.stlf$mean) %>% 
#     mutate(dangjin=dangjin.stlf$mean) %>% 
#     mutate(ulsan=ulsan.stlf$mean) %>% 
#     melt(id.var="time") %>% mutate(value=ifelse(value<50, 0, value)) %>% 
#     acast(time~variable) %>% data.frame() %>% 
#     rownames_to_column("time")

```

















