---
title: "introduction `tidymodels` with walmart data"
author: "류성균"
date: '2021 3 6 '
output: html_document
---

- cv는 어떻게?

- reference :
    - []()
    - []()

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
library(magrittr)
library(here)
```


### Tidymodels
 - 소개

### Walmart
```{r}
train <- read_csv(here("walmart/train.csv.zip"))
test <- read_csv(here("walmart/test.csv.zip"))
```

```{r}
train %<>% janitor::clean_names()
test %<>% janitor::clean_names()
```


```{r}
train %>% 
    select(date, weekly_sales) %>% 
    ggplot(aes(x = date, y = weekly_sales)) + 
    geom_line()
```

```{r}
set.seed(1234)
walmart_split <- initial_split(train, prop = 0.7, strata = is_holiday)
walmart_split
```

```{r}
train_wal <- walmart_split %>% training()

val_wal <- walmart_split %>% testing()
```


### Preprocess interface


 - recipe
 - prep
 - step
    - step_corr()
    - step_center
    - step_scale
    

```{r}
walmart_recipe <- train_wal %>% 
    recipe(weekly_sales ~ .) %>% 
    step_date(date, features = c("year", "month", "dow")) %>% 
    step_rm(date)  %>% 
    step_mutate(
            store = as.factor(store),
            dept = as.factor(dept)
            # , date_year = as.factor(date_year)
            ) %>% 
    step_center(all_numeric(), -all_outcomes()) %>%
    step_scale(all_numeric(), -all_outcomes()) %>%
    step_dummy(all_nominal()) %>% 
    prep()

walmart_recipe
```
```{r}
train_final <- juice(walmart_recipe)
train_final %>% colnames()
```
```{r}
walmart_recipe %>% 
    bake(val_wal) %>% 
    colnames()
```

```{r}
walmart_recipe %>% 
    bake(test) %>% 
    colnames()
```



```{r}
lm_model <- 
    linear_reg() %>% 
    set_engine("lm") %>% 
    set_mode("regression")
```


```{r}
walmart_wflow <- workflow() %>% 
    add_model(lm_model) %>% 
    add_recipe(walmart_recipe)

walmart_wflow
```


```{r}
walmart_lmfit <- walmart_wflow %>% 
    fit(train_wal)
```

```{r}
summary(walmart_lmfit)
```


```{r}
walmart_lmfit %>% 
    predict(val_wal) %>% 
    bind_cols(val_wal) %>%  select(weekly_sales,.pred) %>% 
    metrics(truth = weekly_sales, estimate = .pred)
```


```{r}
walmart_lmfit %>% 
    predict(test)
```



- issac's baseline : 20238.71579
- dummy 20297.36816
```{r}
subfile2 <- read_csv(here("walmart/sampleSubmission.csv.zip"))
subfile2$Weekly_Sales <- walmart_lmfit %>% 
    predict(test) %>% 
    select(.pred) %>% unlist()

subfile2
# write.csv(subfile, row.names = FALSE,
#           "./walmart/baseline-lm-02262021.csv")

write.csv(subfile2, row.names = FALSE,
          here("walmart/baseline-lm-dummy.csv"))
```


### random Forest

```{r}
rf_model <- 
    rand_forest() %>% 
    set_engine("ranger") %>% 
    set_mode("regression")

```

```{r}
walmart_wflow <- workflow() %>% 
    add_model(rf_model) %>% 
    add_recipe(walmart_recipe)

walmart_wflow
```



```{r}
walmart_rffit <- walmart_wflow %>% 
    fit(train_wal)

walmart_wflow
```



```{r}
walmart_rffit %>% 
    predict(val_wal) %>% 
    bind_cols(val_wal) %>%  select(weekly_sales,.pred) %>% 
    metrics(truth = weekly_sales, estimate = .pred)
```

- issac's baseline : 20238.71579
- dummy 20297.36816
- rf dummy : 20402.03236
```{r}
subfile <- read_csv(here("walmart/sampleSubmission.csv.zip"))
subfile$Weekly_Sales <- walmart_rffit %>% 
    predict(test) %>% 
    select(.pred) %>% unlist()

subfile
# write.csv(subfile, row.names = FALSE,
#           "./walmart/baseline-lm-02262021.csv")

write.csv(subfile, row.names = FALSE,
          here("walmart/baseline-rf-dummy.csv"))
```


### cv in random forest